<?php
return $cat =
    array(
        array(
            'url'=>'http://www.healthywomen.org/ages-and-stages/healthy-living/diet-and-nutrition',
            'tags'=>'healthy-living,diet-and-nutrition,ages-and-stages',
            'genre'=>'food-fitness',
            'source'=>'healthywomen'
        ),
        array(
            'url'=>'http://www.healthywomen.org/ages-and-stages/healthy-living/recipes',
            'tags'=>'healthy-living,diet-and-nutrition,ages-and-stages,recipes',
            'genre'=>'food-fitness',
            'source'=>'healthywomen'
        ),
        array(
            'url'=>'http://www.healthywomen.org/ages-and-stages/healthy-living/fitness',
            'tags'=>'healthy-living,fitness',
            'genre'=>'health-wellness',
            'source'=>'healthywomen'
        ),
        array(
            'url'=>'http://www.healthywomen.org/ages-and-stages/healthy-living/managing-stress',
            'tags'=>'healthy-living,fitness,managing-stress,ages-and-stages',
            'genre'=>'health-wellness',
            'source'=>'healthywomen'
        ),
        array(
            'url'=>'http://www.healthywomen.org/ages-and-stages/healthy-living/beauty-and-aging',
            'tags'=>'healthy-living,beauty-aging',
            'genre'=>'beauty-aging',
            'source'=>'healthywomen'
        ),
        array(
            'url'=>'http://www.healthywomen.org/ages-and-stages/family-health-and-wellness-guide',
            'tags'=>'healthy-living,family-health,wellness-guide',
            'genre'=>'health-wellness',
            'source'=>'healthywomen'
        ),
    );
